# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/noarch/affine-2.3.0-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/arcgis-1.8.0-py37_1091.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/attrs-19.3.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/backcall-0.1.0-py37_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/bleach-3.1.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/blinker-1.4-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/boost-cpp-1.70.0-h6a4c333_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/branca-0.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/bzip2-1.0.8-hfa6e2cd_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2020.1.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/certifi-2019.11.28-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cffi-1.13.2-py37hb32ad35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/chardet-3.0.4-py37_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-plugins-1.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cligj-0.5.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/colorama-0.4.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/contextily-1.0rc2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cryptography-2.8-py37hb32ad35_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/curl-7.68.0-h4496350_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_2.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/deprecated-1.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/descartes-1.1.0-py_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/entrypoints-0.3-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/expat-2.2.9-he025d50_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/fiona-1.8.4-py37h0d92105_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/folium-0.10.1-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/freetype-2.9.1-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/freexl-1.0.5-hd288d7e_1002.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/gdal-2.3.3-py37hdf43c64_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geographiclib-1.50-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geojson-2.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geopandas-0.7.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geopy-1.21.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/geos-3.7.1-h33f27b4_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/hdf4-4.2.13-h712560f_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/hdf5-1.10.4-nompi_hcc15c50_1106.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icc_rt-2019.0.0-h0cc432a_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/icu-58.2-ha66f8fd_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/idna-2.8-py37_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/importlib_metadata-1.5.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2020.0-166.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipykernel-5.1.4-py37h39e3cac_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipython-7.12.0-py37h5ca1d4c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/ipython_genutils-0.2.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/ipywidgets-7.5.1-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/jedi-0.15.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.11.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/joblib-0.14.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jpeg-9b-hb83a4c4_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jsonschema-3.2.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter-1.0.0-py37_7.tar.bz2
https://conda.anaconda.org/esri/win-64/jupyter_client-5.3.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jupyter_console-6.1.0-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/jupyter_core-4.5.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/kealib-1.4.7-h07cbb95_6.tar.bz2
https://conda.anaconda.org/esri/win-64/keyring-19.0.2-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/kiwisolver-1.1.0-py37he980bc4_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/krb5-1.16.4-hdd46e55_0.tar.bz2
https://conda.anaconda.org/esri/win-64/lerc-0.1.0-py37h39e3cac_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libblas-3.8.0-14_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libcblas-3.8.0-14_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libcurl-7.68.0-h4496350_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libgdal-2.3.3-h10f50ba_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libiconv-1.15-hfa6e2cd_1005.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libkml-1.3.0-h4ece8bf_1010.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/liblapack-3.8.0-14_mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libnetcdf-4.6.1-h411e497_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libpng-1.6.37-h2a8f88b_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libpq-11.5-hb0bdaea_2.tar.bz2
https://conda.anaconda.org/esri/win-64/libsodium-1.0.18-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libspatialindex-1.9.3-he025d50_3.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libspatialite-4.3.0a-h6a0152f_1026.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libssh2-1.8.2-h642c060_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libtiff-4.0.9-hf1753bf_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libxml2-2.9.10-h9ce36c8_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-5.3.0-7.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-core-5.3.0-7.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gmp-6.1.0-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/mapclassify-2.2.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/markupsafe-1.1.1-py37he774522_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/matplotlib-3.1.3-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/matplotlib-base-3.1.3-py37h2981e6d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/mercantile-1.1.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mistune-0.8.4-py37he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2019.4-245.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mkl-service-2.3.0-py37hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/mplleaflet-0.0.5-py_4.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/msys2-conda-epoch-20160418-1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/munch-2.5.0-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/nbconvert-5.5.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/nbformat-5.0.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/networkx-2.4-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/notebook-6.0.1-py37_0.tar.bz2
https://conda.anaconda.org/esri/noarch/ntlm-auth-1.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/numpy-1.18.1-py37hc71023c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/oauthlib-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.1.1d-he774522_4.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/osmnx-0.11.4-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandas-1.0.1-py37he350917_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandocfilters-1.4.2-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/parso-0.6.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pcre-8.44-h6538335_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pickleshare-0.7.5-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pillow-5.4.1-py37hdc69c19_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pip-20.0.2-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/proj-6.3.0-ha7a8c7b_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/proj4-5.2.0-h6538335_1006.tar.bz2
https://conda.anaconda.org/esri/win-64/prometheus_client-0.7.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pycparser-2.19-py37_1.tar.bz2
https://conda.anaconda.org/esri/win-64/pygments-2.4.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyjwt-1.7.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyopenssl-19.1.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.4.6-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyproj-2.4.2.post1-py37hc1560cf_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyqt-5.9.2-py37h6538335_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyrsistent-0.15.7-py37he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyshp-2.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pysocks-1.7.1-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-3.7.6-h60c2a47_2.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2019.3-py_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pywin32-ctypes-0.2.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pywinpty-0.5.7-py37_0.tar.bz2
https://conda.anaconda.org/esri/win-64/pyzmq-18.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/qt-5.9.7-vc14h73c81de_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/qtconsole-4.6.0-py_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/rasterio-1.0.21-py37h6bd7d87_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/requests-2.22.0-py37_1.tar.bz2
https://conda.anaconda.org/esri/win-64/requests-kerberos-0.12.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/requests-oauthlib-1.3.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/requests-toolbelt-0.9.1-py_0.tar.bz2
https://conda.anaconda.org/esri/noarch/requests_ntlm-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/rtree-0.9.4-py37hbf79ddb_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/scikit-learn-0.22.1-py37h7208079_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/scipy-1.3.1-py37h29ff71c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/send2trash-1.5.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/setuptools-45.2.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/shapely-1.6.4-py37h7d20962_1005.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sip-4.19.8-py37h6538335_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/six-1.14.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/snuggs-1.4.7-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.31.1-he774522_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/terminado-0.8.3-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/testpath-0.4.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tk-8.6.10-hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/tornado-6.0.3-py37he774522_3.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/traitlets-4.3.3-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/urllib3-1.25.7-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vc-14.1-h0510ff6_4.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/vincent-0.4.4-py_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.16.27012-hf0eaf9b_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.1.8-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/webencodings-0.5.1-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.34.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/widgetsnbextension-3.5.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/win_inet_pton-1.1.0-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py37_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/winkerberos-0.7.0-py37_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/winpty-0.4.3-4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wrapt-1.12.0-py37hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/xerces-c-3.2.2-h6538335_1004.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/xz-5.2.4-h2fa13f4_1001.tar.bz2
https://conda.anaconda.org/esri/win-64/zeromq-4.3.2-0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/zipp-2.2.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.11-h62dcd97_3.tar.bz2
